
export const TYPES = {
  SET_MESSAGE: 'SET_MESSAGE',
  IMAGES_LOADED: 'IMAGES_LOADED',

  WIFI_INFO_RESET: 'WIFI_INFO_RESET',
  WIFI_SSID: 'WIFI_SSID',
  WIFI_DISCONNECTED: 'WIFI_DISCONNECTED',

  WIFI_SCAN_REQUEST: 'WIFI_SCAN_REQUEST',
  WIFI_SCAN_IN_PROGRESS: 'WIFI_SCAN_IN_PROGRESS',
  WIFI_SCAN_FAIL: 'WIFI_SCAN_FAIL',
  WIFI_SCAN_SUCCESS: 'WIFI_SCAN_SUCCESS',

  WIFI_CONNECT_REQUEST: 'WIFI_CONNECT_REQUEST',
  WIFI_CONNECT_IN_PROGRESS: 'WIFI_CONNECT_IN_PROGRESS',
  WIFI_CONNECT_SUCCESS: 'WIFI_CONNECT_SUCCESS',
  WIFI_CONNECT_FAIL: 'WIFI_CONNECT_FAIL',
}
